language: c++

branches:
  only:
    - master
    - develop

sudo: required
dist: trusty

services:
  - docker

before_install:
    - docker pull fedora:latest
    - docker pull debian:stable

script:
    - >
        docker run --rm -ti -v "${TRAVIS_BUILD_DIR}":/tmp/roc -w /tmp/roc \
            fedora:latest scripts/travis/fedora.sh
    - >
        docker run --rm -ti -v "${TRAVIS_BUILD_DIR}":/tmp/roc -w /tmp/roc \
            debian:stable scripts/travis/debian.sh
