language: generic

branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker pull rocproject/travis-ubuntu:18.04
        - docker pull rocproject/travis-ubuntu:16.04
        - docker pull rocproject/travis-ubuntu:14.04
        - docker pull rocproject/travis-debian
        - docker pull rocproject/travis-fedora
        - docker pull rocproject/travis-centos
        - docker pull rocproject/travis-min
        - docker pull rocproject/cross-arm-bcm2708hardfp-linux-gnueabi:gcc-4.7
        - docker pull rocproject/cross-arm-linux-gnueabihf:gcc-4.9
        - docker pull rocproject/cross-aarch64-linux-gnu:gcc-7.4
      script:
        - scripts/travis/docker.sh rocproject/travis-ubuntu:18.04 scripts/travis/linux/ubuntu-18.04.sh
        - scripts/travis/docker.sh rocproject/travis-ubuntu:16.04 scripts/travis/linux/ubuntu-16.04.sh
        - scripts/travis/docker.sh rocproject/travis-ubuntu:14.04 scripts/travis/linux/ubuntu-14.04.sh
        - scripts/travis/docker.sh rocproject/travis-debian scripts/travis/linux/debian.sh
        - scripts/travis/docker.sh rocproject/travis-fedora scripts/travis/linux/fedora.sh
        - scripts/travis/docker.sh rocproject/travis-centos scripts/travis/linux/centos.sh
        - scripts/travis/docker.sh rocproject/travis-min scripts/travis/linux/min.sh
        - scripts/travis/docker.sh rocproject/cross-arm-bcm2708hardfp-linux-gnueabi:gcc-4.7 scripts/travis/cross/arm-bcm2708hardfp-linux-gnueabi.sh
        - scripts/travis/docker.sh rocproject/cross-arm-linux-gnueabihf:gcc-4.9 scripts/travis/cross/arm-linux-gnueabihf.sh
        - scripts/travis/docker.sh rocproject/cross-aarch64-linux-gnu:gcc-7.4 scripts/travis/cross/aarch64-linux-gnu.sh
        - cat build.status

    - os: osx
      osx_image: xcode7.3
      script:
        - scripts/travis/osx/xcode73.sh

    - os: osx
      osx_image: xcode9.1
      script:
        - scripts/travis/osx/xcode91.sh
