language: c++

branches:
  only:
    - master
    - develop

sudo: required
dist: trusty

services:
  - docker

before_install:
    - docker pull rocproject/ci-fedora
    - docker pull rocproject/ci-debian

script:
    - scripts/travis/docker.sh rocproject/ci-fedora scripts/travis/fedora.sh
    - scripts/travis/docker.sh rocproject/ci-debian scripts/travis/debian.sh
